name: Staging Deploy

on:
  push:
    branches: [ "develop" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Staging Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navegar al directorio del proyecto
            cd ~/peruana-informatica_v2 || exit
            
            # Actualizar código (rama develop)
            git checkout develop
            git pull origin develop
            
            # Inyectar variables de entorno
            echo "${{ secrets.ENV_STAGING }}" > envs/.env.staging
            
            # Desplegar Staging
            docker compose -f docker-compose.yml -f docker-compose.staging.yml down
            docker compose -f docker-compose.yml -f docker-compose.staging.yml up -d --build
